### ISSUE TITLE
Specify Address on signMessage

### ISSUE THREAD

**Issue by Keegan-lee** [omnisat/lasereyes#20]
I would like to be able to specify which bitcoin address to use for signing messages. Right now, UniSat messages are signed with the paymentAddress and xVerse and magicEden are signed with the ordinalsAddress (address).

In order to get consistent default behaviour from all wallets, I recommend defaulting to signing with the paymentAddress, and allowing the user to specify the address in an options param.

**Comment by hathbanger** [comment]
@Keegan-lee ahoy!

it depends on the contents of what you're signing. when signing w xverse in the lib will iterate through each input to find which address it should be signing with. i think adding an optional configuration object would be wise tho, perhaps pass in finalize and broadcast in that as well.

**Comment by hathbanger** [comment]
totally misread this as signPsbt smh, lets update this.
