### ISSUE TITLE
Signet Support

### ISSUE THREAD

**Issue by Keegan-lee** [omnisat/lasereyes#21]
We need to be able to reliably test the wallets on signet. Show and use supported wallets for signet. 

1. Show which wallets support signet
2. Handle connection to a wallet when switching to signet

**Comment by hathbanger** [comment]
i think this is a _**must**_ as well. our only issue is that most of the ordinal friendly wallets are missing signet support atm, but now that i think about, lets put this on the front burner.

**Comment by hathbanger** [comment]
just to keep track. which wallets support signet:
- [x] unisat
- [x] xverse
- [ ] oyl
- [ ] magic eden
- [x] wizz
- [ ] phantom
- [ ] okx

**Comment by hathbanger** [comment]
Looks like signet PubKey is one in the same as a testnet PubKey so we'll need to look into how we'll broadcast (Sandshrew???) and the necessary flags in all of the methods to fill in the gaps created by wallet insufficiencies.

**Comment by hathbanger** [comment]
added here: #40
