### ISSUE TITLE
Include Wallet Logos

### ISSUE THREAD

**Issue by Keegan-lee** [omnisat/lasereyes#25]
I would like to see wallet logos included in the package somewhere so that I have centralized access to the right images, for the right wallets, at the right size.

**Comment by hathbanger** [comment]
@Keegan-lee have this on the radar, grabbed all of OYL's assets the other week in preparation. we'll need each supported wallet's SVGS for each variant. figure we'll make exportable react icons

wallets:
- [x] OYL - [oyl-logos.zip](https://github.com/user-attachments/files/16636670/oyl-logos.zip)
- [x] UNISAT
- [x] XVERSE
- [x] MAGIC EDEN
- [x] WIZZ
- [x] LEATHER - [leather-logos.zip](https://github.com/user-attachments/files/16636669/leather-logos.zip)
- [x] OKX
- [x] PHANTOM

**Comment by hathbanger** [comment]
lets have @0xBunzy tackle this today.
