### ISSUE TITLE
OKX not works

### ISSUE THREAD

**Issue by chezhe** [omnisat/lasereyes#50]
Connect OKX wallet on https://demo.lasereyes.build/ , try signPsbt, get this error

<img width="560" alt="Screenshot 2024-10-10 at 10 30 36" src="https://github.com/user-attachments/assets/c5dfb0c2-d3e9-4bfc-a941-f4ef811da51d">

**Comment by hathbanger** [comment]
@chezhe believed to be fixed in v0.0.79, wanna retest on your end?

**Comment by chezhe** [comment]
Great work! I've upgraded to 0.0.80, got another error(tried OKX and Unisat, same result)

<img width="770" alt="Screenshot 2024-10-11 at 11 27 45" src="https://github.com/user-attachments/assets/49f11a78-da19-41b8-83cf-7c2ce6b72713">

While posting to https://mempool.space/api/tx

**Comment by chezhe** [comment]
According to description https://mempool.space/docs/api/rest#post-transaction, mempool.space accepts raw transaction, instead psbt

**Comment by hathbanger** [comment]
@chezhe was this on demo.lasereyes.builld? or somewhere else?

**Comment by hathbanger** [comment]
repo's moving!

@chezhe mind reopening the issue over here?



https://github.com/omnisat/lasereyes-mono
