### ISSUE TITLE
ReferenceError: _toESM is not defined in Next.js

### ISSUE THREAD

**Issue by martianatwork** [omnisat/lasereyes#51]
I'm using Next.js, getting following error on build:
"ReferenceError: _toESM is not defined"

https://github.com/omnisat/lasereyes/blob/7f36f6f6f643f38a56508018d9c6c561ddf21fd7/dist/index.js#L369

**Comment by hathbanger** [comment]
@martianatwork which version of Next are you running atm?

**Comment by hathbanger** [comment]
repo's moving!

@martianatwork we've rebuilt a lot of the core software, would u mind rechecking t his issue with the new build?

https://github.com/omnisat/lasereyes-mono
