### ISSUE TITLE
createSendBtcPsbt - Change output value miscalculation

### ISSUE THREAD

**Issue by vinkim** [omnisat/lasereyes#52]
https://github.com/omnisat/lasereyes/blob/7f36f6f6f643f38a56508018d9c6c561ddf21fd7/src/lib/helpers.ts#L198C1-L203C4

**Issue**: `amount` is substracted from the change output value twice, since `satsNeeded` already has `amount` included.

**Causes**:
Causes negative numbers if `satsNeeded + amount > amountGathered` or sender not getting back all the change they are supposed to.

```ts
  // satsNeeded takes amount into account.
  const satsNeeded = Math.floor(estTxSize * feeRate) + amount;
 
   ....
   
  // Adding change output to send leftover sats back tos sender.
  if (amountGathered > satsNeeded) {
    psbt.addOutput({
      address: paymentAddress,
      value: amountGathered - satsNeeded - amount, // Here we substract satsNeeded AND amount, even though amount is already part of satsNeeded
    });
  }
```

**Comment by hathbanger** [comment]
great find, @vinkim !!!! wanna open a PR?

**Comment by hathbanger** [comment]
repo's moving!

@vinkim wanna open a new pr for this? i believe the function will be in `/packages/lasereyes-core`

https://github.com/omnisat/lasereyes-mono
